// ---------------------------------------------------------------------------
// Detour core scalar aliases (C++ side):
//   typedef unsigned int dtPolyRef;
//   typedef unsigned int dtTileRef;
//   typedef unsigned int dtStatus;
// In IDL we just use 'long' for these.
// ---------------------------------------------------------------------------

interface dtNavMeshParams {
	// Origin of the navmesh tile grid. [(x, y, z)]
	// C++: float orig[3];
	attribute float[] orig;

	// C++: float tileWidth;
	attribute float tileWidth;

	// C++: float tileHeight;
	attribute float tileHeight;

	// C++: int maxTiles;
	attribute long maxTiles;

	// C++: int maxPolys;
	attribute long maxPolys;
};

// ---------------------------------------------------------------------------
// dtNavMesh
// C++: class dtNavMesh { dtStatus init(...); dtStatus addTile(...); ... }
// Ref: DetourNavMesh.h dtNavMesh, dtNavMeshParams, setPolyFlags/getPolyFlags
// :contentReference[oaicite:1]{index=1}
// ---------------------------------------------------------------------------

interface dtNavMesh {
	// C++: dtNavMesh::dtNavMesh();
	void dtNavMesh();

	// C++: dtStatus init(const dtNavMeshParams* params);
	long init([Const] dtNavMeshParams params);

	// C++: dtStatus init(unsigned char* data, const int dataSize, const int flags);
	// 'data' is a navmesh binary blob.
	// long init( char[] data, long dataSize, long flags);

	// C++: const dtNavMeshParams* getParams() const;
	[Const] dtNavMeshParams getParams();

	// C++: dtStatus addTile(unsigned char* data, int dataSize, int flags,
	//                      dtTileRef lastRef, dtTileRef* result);
	// 'resultRef' receives the resulting dtTileRef.
	long addTile( char[] data, long dataSize, long flags,
	             long lastRef, [Out] uint resultRef);

	// If you really need removeTile, you can expose it, but it uses
	// unsigned char** and int*, which is clumsy from IDL side.
	// C++: dtStatus removeTile(dtTileRef ref, unsigned char** data, int* dataSize);
	// long removeTile(long ref, [Ref] unsigned char[] data, [Ref] long dataSize);

	// C++: void calcTileLoc(const float* pos, int* tx, int* ty) const;
	// 'pos' is length-3 [x,y,z], tx/ty are tile indices.
	[Const] void calcTileLoc(float[] pos, [Const, Out] long tx, [Const, Out] long ty);

	// C++: bool isValidPolyRef(dtPolyRef ref) const;
	[Const] boolean isValidPolyRef(long ref);

	// C++: int getMaxTiles() const;
	[Const] long getMaxTiles();

	// C++: dtStatus setPolyFlags(dtPolyRef ref, unsigned short flags);
	long setPolyFlags(long ref, short flags);

	// C++: dtStatus getPolyFlags(dtPolyRef ref, unsigned short* resultFlags) const;
	[Const] long getPolyFlags(long ref, [Out] short flags);

	// C++: dtStatus setPolyArea(dtPolyRef ref, unsigned char area);
	long setPolyArea(long ref, short area);

	// C++: dtStatus getPolyArea(dtPolyRef ref, unsigned char* resultArea) const;
	[Const] long getPolyArea(long ref, [Out] char area);
};

// ---------------------------------------------------------------------------
// dtQueryFilter
// C++: class dtQueryFilter { setIncludeFlags, setExcludeFlags, setAreaCost, ... }
// Ref: DetourNavMeshQuery.h dtQueryFilter docs. :contentReference[oaicite:2]{index=2}
// ---------------------------------------------------------------------------

interface dtQueryFilter {
	// C++: dtQueryFilter::dtQueryFilter();
	void dtQueryFilter();

	// C++: float getAreaCost(int i) const;
	[Const] float getAreaCost(long i);

	// C++: void setAreaCost(int i, float cost);
	void setAreaCost(long i, float cost);

	// C++: unsigned short getIncludeFlags() const;
	[Const] short getIncludeFlags();

	// C++: void setIncludeFlags(unsigned short flags);
	void setIncludeFlags(short flags);

	// C++: unsigned short getExcludeFlags() const;
	[Const] short getExcludeFlags();

	// C++: void setExcludeFlags(unsigned short flags);
	void setExcludeFlags(short flags);
};

// ---------------------------------------------------------------------------
// dtNavMeshQuery
// C++: class dtNavMeshQuery { init, findPath, findStraightPath, findNearestPoly, ... }
// Ref: dtNavMeshQuery docs. :contentReference[oaicite:3]{index=3}
// ---------------------------------------------------------------------------

interface dtNavMeshQuery {
	// C++: dtNavMeshQuery::dtNavMeshQuery();
	void dtNavMeshQuery();

	// C++: dtStatus init(const dtNavMesh* nav, const int maxNodes);
	long init([Const] dtNavMesh nav, long maxNodes);

	// --- Standard pathfinding ---

	// C++:
	// dtStatus findPath(
	//     dtPolyRef startRef, dtPolyRef endRef,
	//     const float* startPos, const float* endPos,
	//     const dtQueryFilter* filter,
	//     dtPolyRef* path, int* pathCount, const int maxPath) const;
	[Const] long findPath(
		long startRef,
		long endRef,
		float[] startPos,    // [3]
		float[] endPos,      // [3]
		[Const] dtQueryFilter filter,
		uint[] path,   // output polygon refs
		[Out] long pathCount,
		long maxPath
	);

	// C++:
	// dtStatus findStraightPath(
	//     const float* startPos, const float* endPos,
	//     const dtPolyRef* path, const int pathSize,
	//     float* straightPath,
	//     unsigned char* straightPathFlags,
	//     dtPolyRef* straightPathRefs,
	//     int* straightPathCount,
	//     const int maxStraightPath) const;
	[Const] long findStraightPath(
		float[] startPos,          // [3]
		float[] endPos,            // [3]
		uint[] path,               // input poly corridor
		long pathSize,
		float[] straightPath,      // output positions, 3 * N
		char[] straightPathFlags, // DT_STRAIGHTPATH_* (stored in short)
		uint[] straightPathRefs,   // poly refs per point
		[Out] long straightPathCount,
		long maxStraightPath
	);

	// --- Local queries / helpers ---

	// C++:
	// dtStatus findNearestPoly(
	//     const float* center, const float* extents,
	//     const dtQueryFilter* filter,
	//     dtPolyRef* nearestRef, float* nearestPt) const;
	[Const] long findNearestPoly(
		float[] center,          // [3]
		float[] extents,         // [3]
		[Const] dtQueryFilter filter,
		[Out] uint nearestRef,
		float[] nearestPt  // [3]
	);

	// C++:
	// dtStatus moveAlongSurface(
	//     dtPolyRef startRef,
	//     const float* startPos,
	//     const float* endPos,
	//     const dtQueryFilter* filter,
	//     float* resultPos,
	//     dtPolyRef* visited, int* visitedCount,
	//     const int maxVisitedSize) const;
	[Const] long moveAlongSurface(
		long startRef,
		float[] startPos,        // [3]
		float[] endPos,          // [3]
		[Const] dtQueryFilter filter,
		float[] resultPos, // [3]
		uint[] visited,    // visited poly refs
		[Out] long visitedCount,
		long maxVisitedSize
	);

	// C++:
	// dtStatus getPolyHeight(
	//     dtPolyRef ref,
	//     const float* pos,
	//     float* height) const;
	[Const] long getPolyHeight(
		long ref,
		float[] pos,      // [3]
		[Out] float height
	);

	// C++:
	// bool isValidPolyRef(dtPolyRef ref, const dtQueryFilter* filter) const;
	[Const] boolean isValidPolyRef(long ref, [Const] dtQueryFilter filter);

	// C++:
	// const dtNavMesh* getAttachedNavMesh() const;
	[Const] dtNavMesh getAttachedNavMesh();
};
